language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  global:
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
# command to run tests
script:
  - py.test moviepy
after_success:
  - coveralls
